---

# Node role
consul_node_role: server
# Group name
consul_group_name: master
# Add bootstrap expected number
consul_bootstrap_expect: true
consul_bootstrap_expect_value: 1
# Client address, necessary to enable UI
consul_client_address: 0.0.0.0
