version: "3.7"

services:
  terraform:
    image: hashicorp/terraform:${TERRAFORM_VERSION}
    working_dir: /infrastructure
    user: ${USER_ID}
    volumes:
      - ./:/infrastructure
      # Share TF credential file
      - ~/.terraform.d/credentials.tfrc.json:/infrastructure/.terraform.d/credentials.tfrc.json
    environment:
      HOME: /infrastructure
      
      # TERRAFORM ENVIRONMENT VARIABLES
      # Avoid suggesting commands
      TF_IN_AUTOMATION: 'true'
      # Disable prompts for variables that haven't had their values specified
      TF_INPUT: 'false'

      # Terraform CLI arguments
      # TF_CLI_ARGS: ${TF_CLI_ARGS}
      TF_CLI_ARGS_init: ${TF_CLI_ARGS_init}
      TF_CLI_ARGS_apply: ${TF_CLI_ARGS_apply}

      # Scaleway credentials
      SCW_ACCESS_KEY: ${SCW_ACCESS_KEY}
      SCW_SECRET_KEY: ${SCW_SECRET_KEY}
      SCW_DEFAULT_PROJECT_ID: ${SCW_DEFAULT_PROJECT_ID}
      SCW_DEFAULT_ORGANIZATION_ID: ${SCW_DEFAULT_ORGANIZATION_ID}

    # Overwrite 'terraform' entrypoint by nothing
    entrypoint: ''
    # Define the new command to be more flexible
    command: sh -c "terraform ${STEP} ${COMMAND_OPTIONS}"
