---

- hosts: master, client
  become: True
  roles:
    - { role: consul, tags: [ consul ] }
    - { role: nomad, tags: [ nomad ] }

- hosts: client
  become: True
  roles:
    - { role: docker, tags: [ docker ] }
